### ISSUE TITLE
Btw I reported your discord message to my alt

### ISSUE THREAD

**Issue by itsomey** [Project-Rose/project-rose-website#3]
![2024-09-28-14-55-50-342](https://github.com/user-attachments/assets/2f2153a7-67b1-4042-8fca-645d5f1ec803)

**Comment by SkyeDoesThings1** [comment]
keep ddossing me
please

**Comment by SkyeDoesThings1** [comment]
also i do not care if you reported my msg hell idc if i get banned you're not funny and you seriously help. Sending dick pics in the server and ddossing wii u homebrew stuff is not """funny""" you honestly need a reality check, this is a crime. I seriously hope you get help this kinda shit can get you in a hell of a lot of trouble maximum of 10 years in canada btw (90% sure you're canadian) and i hope you do get in trouble with the law for this. its stupid childish behaviour grow up get a life

**Comment by PokeyManatee4** [comment]
Keep roasting him, please
Signed rubies

**Comment by SkyeDoesThings1** [comment]
![image](https://github.com/user-attachments/assets/fc5b6a68-a3b1-492e-9044-da0fe8c89f21)

**Comment by PokeyManatee4** [comment]
The testing site you use could technically charge you for tos breaching

**Comment by SkyeDoesThings1** [comment]
i dont see why you're doing this? Literally no one likes you?? Like is DDoSSing people worth it to make yourself the most hated person in the community??? Do you not have friends? Do your parents not give you enough attention?? Find something healthier to do to get attention rather that DDoSSing 😭

**Comment by PokeyManatee4** [comment]
Skye, i might have something for you, please dm me on discord

**Comment by SkyeDoesThings1** [comment]
alr id have to friend you since we dont have any servers together anymore

**Comment by itsomey** [comment]
Btw I'm not ddosing you rn rubies thinks I am when I'm not lmao

**Comment by itsomey** [comment]
Also 2 steps ahead I'm always 2 steps ahead
